kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: thin-disk
provisioner: kubernetes.io/vsphere-volume
reclaimPolicy: Retain
parameters:
  datastore: LUN01
  diskformat: thin
  fstype: ext4
